### ISSUE TITLE
nmi can be interrupted with ^C

### ISSUE THREAD

**Issue by zevv** [jiro4989/nmi#1]
As we we all know, one of the most important features of `sl` - which is clearly the inspiration for `nmi` - is that it is not uninterruptible by the user. 

I think `nmi` should also  ignore SIGTERM and SIGINT, turning it into the true torture it is ment to be. You mistype? You WAIT!

**Comment by jiro4989** [comment]
@zevv Thanks. I updated. `nmi` ignores SIGTERM and SIGINT now.

**Comment by zevv** [comment]
Quoting jiro (2020-07-29 15:23:31)
> @zevv Thanks. I updated. `nmi` ignores SIGTERM and SIGINT now.

:)

--
:wq
^X^Cy^K^X^C^C^C^C
